# Generated by Django 5.1.3 on 2024-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_paymentmethod_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='user',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_method',
            new_name='payment_methodID',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('debit', 'Debit')], max_length=50),
        ),
    ]
