# Generated by Django 5.1.3 on 2024-12-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_user_paymentmethod_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='processor',
            field=models.CharField(choices=[('none', 'None'), ('visa', 'VISA'), ('mastercard', 'Mastercard'), ('am', 'American Express'), ('discovery', 'Discovery')], max_length=100),
        ),
    ]
