# Generated by Django 5.1.3 on 2024-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_paymentmethod_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('gas', 'Gas'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('earned', 'Earned income'), ('passive', 'Passive income'), ('porfolio', 'Portfolio income'), ('other', 'Other')], max_length=50),
        ),
    ]
