# Generated by Django 5.1.3 on 2025-01-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('vehicle', 'Vehicle'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('shopping', 'Shopping'), ('financial', 'Financial Expenses'), ('food', 'Food and Drinks'), ('earned', 'Earned income'), ('passive', 'Passive income'), ('porfolio', 'Portfolio income'), ('other', 'Other')], max_length=50),
        ),
    ]
