# Generated by Django 5.1.3 on 2025-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='repeat_interval',
            field=models.CharField(choices=[('none', 'One Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
